# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://192.168.64.3/sit/Login.html")
    self.driver.set_window_size(550, 691)
    self.driver.find_element(By.ID, "form-username").click()
    self.driver.find_element(By.ID, "form-username").send_keys("hello")
    self.driver.find_element(By.ID, "form-password").click()
    self.driver.find_element(By.ID, "form-password").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.ID, "form-username").click()
    self.driver.find_element(By.ID, "form-username").click()
    element = self.driver.find_element(By.ID, "form-username")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "form-username").send_keys("test")
    self.driver.find_element(By.ID, "form-password").click()
    self.driver.find_element(By.ID, "form-password").click()
    element = self.driver.find_element(By.ID, "form-password")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "form-password").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    dropdown = self.driver.find_element(By.ID, "ticket_status")
    dropdown.find_element(By.XPATH, "//option[. = 'New']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ticket_status > option:nth-child(2)").click()
    dropdown = self.driver.find_element(By.ID, "ticket_status")
    dropdown.find_element(By.XPATH, "//option[. = 'New']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ticket_status > option:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".filter-group > label:nth-child(1)").click()
    dropdown = self.driver.find_element(By.ID, "ticket_status")
    dropdown.find_element(By.XPATH, "//option[. = 'Work In Progress']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ticket_status > option:nth-child(3)").click()
    dropdown = self.driver.find_element(By.ID, "ticket_status")
    dropdown.find_element(By.XPATH, "//option[. = 'Completed']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ticket_status > option:nth-child(5)").click()
    dropdown = self.driver.find_element(By.ID, "ticket_status")
    dropdown.find_element(By.XPATH, "//option[. = 'Completed']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#ticket_status > option:nth-child(5)").click()
    dropdown = self.driver.find_element(By.ID, "ticket_status")
    dropdown.find_element(By.XPATH, "//option[. = 'Canceled']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-warning").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("michael ")
    self.driver.find_element(By.ID, "insert_form").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("mechail@test.com")
    self.driver.find_element(By.ID, "number").send_keys("TESt1")
    self.driver.find_element(By.ID, "phone").click()
    self.driver.find_element(By.ID, "phone").send_keys("9081223456")
    self.driver.find_element(By.ID, "subject").click()
    self.driver.find_element(By.ID, "subject").send_keys("brokedn screen")
    self.driver.find_element(By.ID, "schedule").click()
    self.driver.find_element(By.ID, "schedule").send_keys("2020-12-10")
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("need to buy new screen")
    self.driver.find_element(By.ID, "cost").click()
    self.driver.find_element(By.ID, "cost").send_keys("135")
    self.driver.find_element(By.ID, "insert").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\34 6 > .material-icons").click()
    self.driver.find_element(By.CSS_SELECTOR, "td > #subject").click()
    self.driver.find_element(By.CSS_SELECTOR, "td > #subject").send_keys("broken screen")
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "td > #status")
    dropdown.find_element(By.XPATH, "//option[. = 'Work In Progress']").click()
    self.driver.find_element(By.CSS_SELECTOR, "td option:nth-child(3)").click()
    self.driver.find_element(By.ID, "update").click()
  
